web:
    image: wordpress
    links:
     - mysql
    environment:
     - WORDPRESS_DB_PASSWORD=<password_>
    working_dir: /var/www/html
    volumes:
     - /ubuntu/wordpress/wpcontent/:/var/www/html/wp-content
     - /ubuntu/wordpress/scdhub_db1.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
     - "80:80"
mysql:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=<password_>
     - MYSQL_DATABASE=wordpress
