web:
    image: wordpress
    links:
     - mysql
    environment:
     - WORDPRESS_DB_PASSWORD=ururE3#2EtY5%y:hT%d@a
    working_dir: /var/www/html
    volumes:
     - /root/wordpress/wpcontent/:/var/www/html/wp-content
     - /root/wordpress/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
     - "80:80"
mysql:
    image: mariadb
    environment:
     - MYSQL_ROOT_PASSWORD=ururE3#2EtY5%y:hT%d@a
     - MYSQL_DATABASE=wordpress
